[main]
name=domoai-knx-gateway
addr=1.0.230
client-addrs=1.0.231:8
connections=server,kv,local
cache=cache

[cache]
max-size=256

[server]
server=ets_router
discover=true
debug=debug-server
tunnel=tunnel
interface=0.0.0.0
port=3672
heartbeat-timeout=90

[tunnel]
filters=log

[debug-server]
name=domoai-knx-gateway
error-level=6
trace-mask=0x42

[kv]
driver=ipt
ip-address=172.26.80.1
dest-port=3671
nat=true
nat-ip=192.168.65.3
src-port=3673
data-port=3673
heartbeat-timer=30
heartbeat-retries=3
debug=debug-kv
filters=monitor,log,single,retry-filter

[debug-kv]
name=kv
error-level=0xff
trace-mask=0xff

[local]
server=knxd_unix
path=/run/knx

[retry-filter]
filter=retry
max-retries=0
retry-delay=2
start-timeout=10
may-fail=true
